apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: read-pipelines
  namespace: openshift-pipelines
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
      - pods
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipelines-prometheus-k8s
  namespace: openshift-pipelines
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: read-pipelines
subjects:
  - kind: ServiceAccount
    name: prometheus-k8s
    namespace: openshift-monitoring